name: flutter_design_patterns_talk
description: Fluter Design Patterns example app for the conference talk.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  go_router: ^3.0.4
  provider: ^6.0.2
  stack: ^0.2.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
